"""
Ontology Specification Tests for Scimantic

These tests validate that SHACL shapes correctly implement the ontology specification
defined in schema/scimantic.yaml and specification documentation.

This is the OUTER LOOP of TDD for ontology development:
1. Write specification tests based on schema/scimantic.yaml
2. Implement SHACL constraints in schema
3. When these tests pass, the ontology specification is correctly implemented
4. Then move to INNER LOOP: implement MCP tools that produce compliant RDF

These tests are EXECUTABLE SPECIFICATIONS, not just SHACL validators.
"""

from rdflib import Graph, Namespace, URIRef, Literal
from rdflib.namespace import PROV, RDF, RDFS
import pytest

SCIMANTIC = Namespace("http://scimantic.io/")


# =============================================================================
# QuestionFormation Activity Specification Tests
# =============================================================================
#
# Constraints:
# - Question.wasGeneratedBy must point to QuestionFormation (if present)
# - Question.label is required
# - Question.motivates must point to LiteratureSearch (if present)
# - QuestionFormation.wasInformedBy must point to ResultAssessment (if present)
# =============================================================================


class TestQuestionFormationPositive:
    """Tests for valid QuestionFormation graphs that should pass SHACL validation."""

    def test_minimal_valid_question(self, validate_with_shacl):
        """
        A Question with only required fields should pass validation.

        Required: label
        """
        g = Graph()
        g.bind("scimantic", SCIMANTIC)

        question_uri = URIRef("http://example.org/question_001")
        g.add((question_uri, RDF.type, SCIMANTIC.Question))
        g.add((question_uri, RDFS.label, Literal("Can DCS be computed using MQDO?")))

        # Should pass - minimal valid Question
        validate_with_shacl(g)

    def test_question_generated_by_question_formation(self, validate_with_shacl):
        """
        A Question generated by QuestionFormation should pass validation.

        Constraint: wasGeneratedBy range must be QuestionFormation
        """
        g = Graph()
        g.bind("scimantic", SCIMANTIC)
        g.bind("prov", PROV)

        question_uri = URIRef("http://example.org/question_001")
        activity_uri = URIRef("http://example.org/qf_001")

        # Question with label
        g.add((question_uri, RDF.type, SCIMANTIC.Question))
        g.add((question_uri, RDFS.label, Literal("Can DCS be computed using MQDO?")))

        # Generated by QuestionFormation
        g.add((activity_uri, RDF.type, SCIMANTIC.QuestionFormation))
        g.add((question_uri, PROV.wasGeneratedBy, activity_uri))

        # Should pass - correct Activity type
        validate_with_shacl(g)

    def test_question_motivates_literature_search(self, validate_with_shacl):
        """
        A Question that motivates a LiteratureSearch should pass validation.

        Constraint: motivates range must be LiteratureSearch
        """
        g = Graph()
        g.bind("scimantic", SCIMANTIC)

        question_uri = URIRef("http://example.org/question_001")
        search_uri = URIRef("http://example.org/search_001")

        # Question
        g.add((question_uri, RDF.type, SCIMANTIC.Question))
        g.add((question_uri, RDFS.label, Literal("Can DCS be computed using MQDO?")))

        # Motivates LiteratureSearch
        g.add((search_uri, RDF.type, SCIMANTIC.LiteratureSearch))
        g.add((question_uri, SCIMANTIC.motivates, search_uri))

        # Should pass - correct range for motivates
        validate_with_shacl(g)

    def test_question_formation_with_agent(self, validate_with_shacl):
        """
        A QuestionFormation activity with an associated agent should pass validation.

        Constraint: wasAssociatedWith range must be Agent
        """
        g = Graph()
        g.bind("scimantic", SCIMANTIC)
        g.bind("prov", PROV)

        activity_uri = URIRef("http://example.org/qf_001")
        agent_uri = URIRef("http://example.org/researcher_001")

        # QuestionFormation activity
        g.add((activity_uri, RDF.type, SCIMANTIC.QuestionFormation))

        # Associated with Agent
        g.add((agent_uri, RDF.type, PROV.Agent))
        g.add((activity_uri, PROV.wasAssociatedWith, agent_uri))

        # Should pass - valid agent association
        validate_with_shacl(g)

    def test_question_formation_informed_by_result_assessment(
        self, validate_with_shacl
    ):
        """
        A QuestionFormation informed by ResultAssessment should pass validation.

        Constraint: wasInformedBy range must be ResultAssessment (if present)
        """
        g = Graph()
        g.bind("scimantic", SCIMANTIC)
        g.bind("prov", PROV)

        qf_uri = URIRef("http://example.org/qf_001")
        ra_uri = URIRef("http://example.org/ra_001")

        # QuestionFormation
        g.add((qf_uri, RDF.type, SCIMANTIC.QuestionFormation))

        # Informed by ResultAssessment
        g.add((ra_uri, RDF.type, SCIMANTIC.ResultAssessment))
        g.add((qf_uri, PROV.wasInformedBy, ra_uri))

        # Should pass - correct Activity type for wasInformedBy
        validate_with_shacl(g)


class TestQuestionFormationNegative:
    """Tests for invalid QuestionFormation graphs that should fail SHACL validation."""

    def test_question_generated_by_wrong_activity_fails(self, validate_with_shacl):
        """
        Test that SHACL fails if a Question is generated by the wrong Activity type.

        Constraint: Question.wasGeneratedBy -> QuestionFormation
        Violation: Question.wasGeneratedBy -> Analysis
        """
        g = Graph()
        g.bind("scimantic", SCIMANTIC)
        g.bind("prov", PROV)

        question_uri = URIRef("http://example.org/bad_question")
        activity_uri = URIRef("http://example.org/bad_activity")

        # Question with label
        g.add((question_uri, RDF.type, SCIMANTIC.Question))
        g.add((question_uri, RDFS.label, Literal("Bad question")))

        # Link it to an Analysis (Wrong Activity Type)
        g.add((activity_uri, RDF.type, SCIMANTIC.Analysis))  # Wrong Type!
        g.add((question_uri, PROV.wasGeneratedBy, activity_uri))

        # Expect Validation Failure
        with pytest.raises(AssertionError) as excinfo:
            validate_with_shacl(g)

        error_msg = str(excinfo.value)
        print(f"\nCaught Expected Validation Error:\n{error_msg}")

        # Check that the error mentions QuestionFormation or class constraint
        assert (
            "QuestionFormation" in error_msg
            or "sh:ClassConstraintComponent" in error_msg
        )

    def test_question_without_label_fails(self, validate_with_shacl):
        """
        Test that SHACL fails if a Question is missing required label.

        Constraint: Question.label is required
        Violation: Question without rdfs:label
        """
        g = Graph()
        g.bind("scimantic", SCIMANTIC)

        question_uri = URIRef("http://example.org/bad_question")

        # Question without label
        g.add((question_uri, RDF.type, SCIMANTIC.Question))
        # Missing: g.add((question_uri, RDFS.label, Literal("...")))

        # Expect Validation Failure
        with pytest.raises(AssertionError) as excinfo:
            validate_with_shacl(g)

        error_msg = str(excinfo.value)
        print(f"\nCaught Expected Validation Error:\n{error_msg}")

        # Check that error mentions label or required property
        assert (
            "label" in error_msg.lower() or "MinCountConstraintComponent" in error_msg
        )

    def test_question_motivates_wrong_activity_fails(self, validate_with_shacl):
        """
        Test that SHACL fails if Question.motivates points to wrong Activity type.

        Constraint: Question.motivates -> LiteratureSearch
        Violation: Question.motivates -> Analysis
        """
        g = Graph()
        g.bind("scimantic", SCIMANTIC)

        question_uri = URIRef("http://example.org/bad_question")
        activity_uri = URIRef("http://example.org/bad_activity")

        # Question
        g.add((question_uri, RDF.type, SCIMANTIC.Question))
        g.add((question_uri, RDFS.label, Literal("Bad question")))

        # Motivates wrong activity type
        g.add((activity_uri, RDF.type, SCIMANTIC.Analysis))  # Wrong Type!
        g.add((question_uri, SCIMANTIC.motivates, activity_uri))

        # Expect Validation Failure
        with pytest.raises(AssertionError) as excinfo:
            validate_with_shacl(g)

        error_msg = str(excinfo.value)
        print(f"\nCaught Expected Validation Error:\n{error_msg}")

        # Check that error mentions LiteratureSearch or class constraint
        assert (
            "LiteratureSearch" in error_msg
            or "sh:ClassConstraintComponent" in error_msg
        )

    def test_question_formation_informed_by_wrong_activity_fails(
        self, validate_with_shacl
    ):
        """
        Test that SHACL fails if QuestionFormation.wasInformedBy points to wrong Activity.

        Constraint: QuestionFormation.wasInformedBy -> ResultAssessment
        Violation: QuestionFormation.wasInformedBy -> Analysis
        """
        g = Graph()
        g.bind("scimantic", SCIMANTIC)
        g.bind("prov", PROV)

        qf_uri = URIRef("http://example.org/bad_qf")
        activity_uri = URIRef("http://example.org/bad_activity")

        # QuestionFormation
        g.add((qf_uri, RDF.type, SCIMANTIC.QuestionFormation))

        # Informed by wrong activity type
        g.add((activity_uri, RDF.type, SCIMANTIC.Analysis))  # Wrong Type!
        g.add((qf_uri, PROV.wasInformedBy, activity_uri))

        # Expect Validation Failure
        with pytest.raises(AssertionError) as excinfo:
            validate_with_shacl(g)

        error_msg = str(excinfo.value)
        print(f"\nCaught Expected Validation Error:\n{error_msg}")

        # Check that error mentions ResultAssessment or class constraint
        assert (
            "ResultAssessment" in error_msg
            or "sh:ClassConstraintComponent" in error_msg
        )
