from rdflib import Graph, Namespace, URIRef
from rdflib.namespace import PROV, RDF
import pytest

SCIMANTIC = Namespace("http://scimantic.io/")


def test_question_generated_by_wrong_activity_fails(validate_with_shacl):
    """
    Test that SHACL fails if a Question is generated by the wrong Activity type.

    Constraint: Question -> prov:wasGeneratedBy -> QuestionFormation
    Violation: Question -> prov:wasGeneratedBy -> Analysis
    """
    g = Graph()
    g.bind("scimantic", SCIMANTIC)
    g.bind("prov", PROV)

    question_uri = URIRef("http://example.org/bad_question")
    activity_uri = URIRef("http://example.org/bad_activity")

    # 1. Create a Question
    g.add((question_uri, RDF.type, SCIMANTIC.Question))

    # 2. Link it to an Analysis (Wrong Activity Type)
    g.add((activity_uri, RDF.type, SCIMANTIC.Analysis))  # Wrong Type!
    g.add((question_uri, PROV.wasGeneratedBy, activity_uri))

    # 3. Expect Validation Failure
    # We assert checks that validate_with_shacl raises an AssertionError
    with pytest.raises(AssertionError) as excinfo:
        validate_with_shacl(g)

    error_msg = str(excinfo.value)
    print(f"\nCaught Expected Validation Error:\n{error_msg}")

    # Check that the specific message from the SHACL shape appears
    # Check that the error mentions the relevant class or property
    assert (
        "QuestionFormation" in error_msg or "sh:ClassConstraintComponent" in error_msg
    )
